baseURL = '//zhan.co.nl/'
languageCode = 'en-us'
title = 'Ying Kun Zhan'
theme = "m10c"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = 'G-8P8VVD04MT'

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
    [[menu.main]]
        identifier = "Keyboards"
        name = "Keyboards"
        url = "/posts/2022-08-04-keyboard-builds/"
        weight = 3

[params]
    author = "Ying Kun Zhan"
    description = "Dad, software engineer, keyboard builder."
    avatar = ""
    menu_item_separator = " - "

    [[params.social]]
        icon = "github"
        name = "My Github"
        url = "https://github.com/ykz89"
    [[params.social]]
        icon = "linkedin"
        name = "My LinkedIn"
        url = "https://www.linkedin.com/in/ying-kun-z-06184473/"
    [[params.social]]
        icon = "mail"
        name = "Send me an email"
        url = "mailto:yingkun@zhan.co.nl"
    [params.style]
        darkestColor = "#242930"
        darkColor = "#353b43"
        lightColor = "#afbac4"
        lightestColor = "#ffffff"
        primaryColor = "#1db4ce"